# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_JZ4740_QI_LB60)	+= qi_lb60.dtb
dtb-$(CONFIG_JZ4740_RS90)	+= rs90.dtb
dtb-$(CONFIG_JZ4770_GCW0)	+= gcw0.dtb
dtb-$(CONFIG_JZ4780_CI20)	+= ci20.dtb
dtb-$(CONFIG_JZ4740_NOAH_NP1380)	+= noah_np1380.dtb
dtb-$(CONFIG_JZ4740_NOAH_NP1500)	+= noah_np1500.dtb
dtb-$(CONFIG_JZ4740_NOAH_NP1501)	+= noah_np1501.dtb
dtb-$(CONFIG_JZ4740_NOAH_NP2150)	+= noah_np2150.dtb
dtb-$(CONFIG_X1000_CU1000_NEO)	+= cu1000-neo.dtb
dtb-$(CONFIG_X1830_CU1830_NEO)	+= cu1830-neo.dtb

obj-$(CONFIG_BUILTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
